# -*- coding: utf-8 -*-
"""Project Finding Visualizations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUApZIZ_4Q2nyAY6abFPUdDnWAi-tnAO
"""

from google.colab import files
uploaded = files.upload()

# visualize_outputs.py
# Purpose: Load Rust-exported CSVs and generate visual plots

import pandas as pd
import matplotlib.pyplot as plt
import csv

# Load CSVs exported from Rust
score_by_genre = pd.read_csv("score_gap_by_genre.csv")
score_by_decade = pd.read_csv("score_gap_by_decade.csv")
degree_centrality = pd.read_csv("degree_centrality.csv", quoting=csv.QUOTE_MINIMAL, on_bad_lines='skip')

# Clean and sort data
score_by_genre = score_by_genre.sort_values("value", ascending=False).head(15)
score_by_decade = score_by_decade.sort_values("key")
top_centrality = degree_centrality.sort_values("value", ascending=False).head(10)

# Plot 1: Average Score Gap by Genre
plt.figure(figsize=(12, 6))
plt.bar(score_by_genre["key"], score_by_genre["value"])
plt.title("Average Score Gap by Genre (User - Critic)")
plt.ylabel("Score Gap")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("score_gap_by_genre_plot.png")

# Plot 2: Average Score Gap by Decade
plt.figure(figsize=(10, 5))
plt.plot(score_by_decade["key"], score_by_decade["value"], marker="o")
plt.title("Average Score Gap by Decade")
plt.xlabel("Decade")
plt.ylabel("Score Gap")
plt.grid(True)
plt.tight_layout()
plt.savefig("score_gap_by_decade_plot.png")

# Plot 3: Top 10 Movies by Degree Centrality
plt.figure(figsize=(12, 6))
plt.barh(top_centrality["key"], top_centrality["value"])
plt.title("Top 10 Movies by Degree Centrality")
plt.xlabel("Connections to Similar Movies")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("top_degree_centrality_plot.png")

